version: '3.8'

services:
  ivr-gs:
    build: .
    image: ivr-gs:latest
    container_name: ivr-gs
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=${DISPLAY}
    volumes:
      - ./Data:/workspace/iVR-GS/Data
      - ./output:/workspace/iVR-GS/output
      - ./exp_scripts:/workspace/iVR-GS/exp_scripts
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ipc: host
    network_mode: host
    stdin_open: true
    tty: true